project:
  type: website
  output-dir: docs
  
website:
  title: "blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/krasing
format:
  html:
    theme:
      - brand
    css: styles.css






